### ISSUE TITLE
NameError: global name 'file_obj_id' is not defined

### ISSUE THREAD

**Issue by cirrus528** [MAECProject/cuckoo#12]
Hi,

I have configured Cuckoo 2.0.6, and wanted to integrate it with maecreport.py. I have followed and configured all the required steps. However, it does not run and prompts an error after each analysis.

2018-10-16 23:52:01,062 [cuckoo.core.plugins] ERROR: Failed to run the reporting module: MaecReport
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/plugins.py", line 623, in process
    current.run(self.results)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/reporting/maecreport.py", line 114, in run
    self.setup()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/reporting/maecreport.py", line 133, in setup
    self.setupPrimaryMalwareInstance()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/reporting/maecreport.py", line 216, in setupPrimaryMalwareInstance
    self.package['observable_objects'][file_obj_id]['extensions'] = {}
NameError: global name 'file_obj_id' is not defined

Can someone help me? Much appreciated, thanks in advance

**Comment by ikiril01** [comment]
Hi @cirrus528, I believe this should be fixed in https://github.com/MAECProject/cuckoo/commit/5602e1bbaeea11418726e834f1300ca0a0690b0f

Let me know if it works now and please report any further issues :)

**Comment by cirrus528** [comment]
Hi @ikiril01, thanks for your help. The reporting works for now when uploaded with an exe file to Cuckoo. 

However, when running analysis with URL, maecreport does not run as intended. 

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/plugins.py", line 623, in process
    current.run(self.results)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/reporting/maecreport.py", line 114, in run
    self.setup()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/reporting/maecreport.py", line 133, in setup
    self.setupPrimaryMalwareInstance()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/reporting/maecreport.py", line 221, in setupPrimaryMalwareInstance
    "value": self.results['target']['url']
NameError: global name 'malawareInstance' is not defined

Hope you can solve it soon :)

**Comment by cirrus528** [comment]
Oops, apologize for not looking at the code carefully. There seems to be a typo in one of the "malwareInstance" on Line 219. Nonetheless, everything is working well as expected.

**Comment by ikiril01** [comment]
Ah, good catch! Thanks for tracking it down, I'll fix it in our repo here as well.
