### ISSUE TITLE
Cuckoo only creates MAEC report 50% of the time.

### ISSUE THREAD

**Issue by fugitive101** [MAECProject/cuckoo#20]
cuckoo 2.0.7 only creates a MAEC report less than half of the time. I also tried to run the same sample many times to see if it will eventually create a report but it does not. The issue seems to be specific so samples.

The full error:
Traceback (most recent call last):
File "/home/user/venv/cuckoo/lib/python2.7/site-packages/cuckoo/core/plugins.py", line 659, in process
current.run(self.results)
File "/home/user/venv/cuckoo/lib/python2.7/site-packages/cuckoo/reporting/maecreport.py", line 159, in run
self.add_dropped_files()
File "/home/user/venv/cuckoo/lib/python2.7/site-packages/cuckoo/reporting/maecreport.py", line 281, in add_dropped_files
malwareInstance = self.create_malware_instance(f)
File "/home/user/venv/cuckoo/lib/python2.7/site-packages/cuckoo/reporting/maecreport.py", line 193, in create_malware_instance
file_obj_id, file_obj = self.create_file_obj(file_data)
File "/home/user/venv/cuckoo/lib/python2.7/site-packages/cuckoo/reporting/maecreport.py", line 333, in create_file_obj
self.create_avc_class_obj_list(cuckoo_file_dict['virustotal'])
File "/home/user/venv/cuckoo/lib/python2.7/site-packages/cuckoo/reporting/maecreport.py", line 615, in create_avc_class_obj_list
for vendor, scan_obj in cuckoo_virusTotal_dict['scans'].items():
KeyError: 'scans'

Is it something that I am doing wrong?
I have processed 500 samples and received only 220 reports.
90% of the time the error is the one above.

**Issue was resolved by disabling virustotal processing module.**

**Comment by emmanvg** [comment]
@fugitive101, it should be fixed and you can re-enable virustotal.
